name = input("Hello, what's your name: ")
print(f"Hello,{name} now you will be making a story!")
print("")
print("")
adjective2 = input("pick a adjective: ")
animal = input("pick an animal: ")
verb2 = input("pick a verb ending in past tense: ")
city = input("pick a city: ")
number = input("pick a number: ")
adjective3 = input("pick an adjective: ")
food = input("pick a food: ")
animal2 = input("pick another animal: ")
emotion = input("pick an emotion: ")
adjective = input("pick an adjective: ")
verb = input("pick a verb ending in past tense: ")
building = input("pick a building: ")
print("")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("")
print(f"Once upon a time, there was a {adjective2} {animal} named {name}, one day {name} {verb2} to {city}. in {city}, {name} bought {number} {adjective3} servings its favorite food,")
print(f"{food} and shared the food with its friend {animal2}, after they finished eating they were both very {emotion} so the two {adjective} animals")
print(f"{verb} to the {building}")
print("")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")