name = input("Hello, what's your name: ")
print(f"Hello,{name} now you will be making a story!")
print("")
print("")
animal = input("pick an animal: ")
city = input("pick a city: ")
number = input("pick a number: ")
food = input("pick a food: ")
animal2 = input("pick another animal: ")
emotion = input("pick an emotion: ")
adjective = input("pick an adjective: ")
verb = input("pick a verb: ")
print("")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("")
print(f"once upon a time, there was a {animal} named {name}, one day {name} went to {city}. in {city}, {name} bought {number} servings its favorite food,")
print(f"{food} and shared the food with its friend {animal2}, after they finished eating they were both very {emotion} so the two {adjective} animals")
print(f"{verb} home")